spring:
  datasource:
#    hikari:
#      connectionTimeout: 20000
#      maximumPoolSize: 1
#      url: jdbc:mariadb://localhost:3306/ISSUE_TRACKING_SYSTEM
#      username: root
#      password: mysql


  application:
    name: issue-service
#    datasource:
#      url: jdbc:mariadb://localhost:3306/ISSUE_TRACKING_SYSTEM
#      username: root
#      password: mysql
#      pool-size: 30
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
  mvc:
    dispatch-options-request: true
  zipkin:
    enabled: false

management:
  endpoint:
    health:
      show-details: always

authorization:
  enabled: false

logbook:
  include:
    - /api/**
  exclude:
    - /actuator/**
  filter.enabled: true
#  secure-filter.enabled: false
  format.style: json
  strategy: without-body
  minimum-status: 200
server:
  port: 8080
  servlet:
    context-path: /api